name: Automatisch EPG aktualisieren

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Code auschecken
      uses: actions/checkout@v5

    - name: Python einrichten
      uses: actions/setup-python@v6
      with:
        python-version: '3.x'

    - name: EPG Skript ausfuehren
      run: python merge_epg.py
      
    - name: Generierte EPG Datei im Repository speichern
      run: |
        git config --global user.name 'EPG Bot'
        git config --global user.email 'bot@github.com'
        git add epg.xml verfuegbare_sender.txt  
        git diff --quiet && git diff --staged --quiet || (git commit -m "EPG und Senderliste automatisch aktualisiert" && git push)
