name: Automatisch EPG aktualisieren

on:
  schedule:
    # Läuft jeden Tag um 04:00 Uhr nachts (UTC Zeit)
    - cron: '0 4 * * *'
  workflow_dispatch: # Ermöglicht es, das Skript jederzeit manuell zu starten

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Code auschecken
      uses: actions/checkout@v4

    - name: Python einrichten
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: EPG Skript ausfuehren
      run: python merge_epg.py

    - name: Generierte EPG Datei im Repository speichern
      run: |
        git config --global user.name 'EPG Bot'
        git config --global user.email 'bot@github.com'
        git add epg.xml
        git diff --quiet && git diff --staged --quiet || (git commit -m "EPG automatisch aktualisiert" && git push)
